### ISSUE TITLE
No access rights to submodule

### ISSUE THREAD

**Issue by christopher-buss** [NansPellicari/UE4-TPL-CppWithTestEnv#3]
When using `git submodule update --init --recursive`, the terminal throws a no correct access rights response.

```
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:NansPellicari/UE4-GoogleTest.git' into submodule path 'C:/Users/chris/Documents/Unreal Projects/MyNewGame/Plugins/GoogleTest' failed
```

Unsure of the steps to allow access to users other than yourself, as I can see the files perfectly fine on GitHub.

**Comment by NansPellicari** [comment]
Oh weird...
1. Maybe a stupid question but just in case, did you check if your ssh key is fresh in your github account? https://stackoverflow.com/questions/25957125/git-submodule-permission-denied
2. Before calling the command `git submodule update --init --recursive`, did you well execute this one  `git submodule init`? I ask for this because in the last PR I fixed a typo in the doc relative to this command, so just in case it has messed up your install process.
3. Otherwise, did you try to change the **ssh** url to the **https** located in the `.gitmodules` file?
this https://github.com/NansPellicari/UE4-GoogleTest.git instead of git@github.com:NansPellicari/UE4-GoogleTest.git

**Comment by NansPellicari** [comment]
Hi @christopher-buss,
Did i considered it's working for you now? May I close this issue and merge the PR?

**Comment by christopher-buss** [comment]
Apologies, I have been rather busy this weekend. I will test this out today and get back to you by the end of the day.

**Comment by NansPellicari** [comment]
> Apologies, I have been rather busy this weekend. I will test this out today and get back to you by the end of the day.

Ah ok sorry, don't worry take you time!

**Comment by christopher-buss** [comment]
I did not have my SSH key correctly set up - which I now do. I switched to fix/submodule and reran the program. the .gitmodules file now has the https.

When I ran the git submodule init command though, it said: 
Submodule 'Plugins/GoogleTest' (git@github.com:NansPellicari/UE4-GoogleTest.git) registered for path 'Plugins/GoogleTest' - it is still trying to use the git@github command. 

I am still getting access denied errors.

**Comment by NansPellicari** [comment]
Ah ok, can you check the file `.git/config` and check the section `[submodule "Plugins/GoogleTest"]`? You probably have the url `git@github.com:NansPellicari/UE4-GoogleTest.git` already configured here. 
You can try to use these commands directly to sync `.gitmodules` with `.git/config`:
```
git submodule sync
git submodule update --init --recursive --remote
```
If it's still not working try to replace the **ssh** url to the **https** in  the file `.git/config` and redo the last commands.

**Comment by christopher-buss** [comment]
Fixed it! The issue was with windows terminal. I was just using the standard terminal, and for some reason, it does not ask the user for their ssh password when you try to clone. When I swapped over to git bash, it asked me for my password, and then gave permissions. Lesson learned, don't use windows 😜

**Comment by NansPellicari** [comment]
> Fixed it! The issue was with windows terminal. I was just using the standard terminal, and for some reason, it does not ask the user for their ssh password when you try to clone. When I swapped over to git bash, it asked me for my password, and then gave permissions. Lesson learned, don't use windows 

Oh ok but with the **https** url you no longer need to use any ssh password, this is for this reason I create this PR. 

Btw: You should not need to provide your ssh password if you have well configured your github account and provide your `.ssh/id_rsa.pub` ([here](https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) how to generate one) in **Settings > SSH and GPG keys**.
For this you should primarily install & use the new built-in ssh client in windows 10 (OpenSSH) https://www.howtogeek.com/336775/how-to-enable-and-use-windows-10s-built-in-ssh-commands/ . This way you can use ssh and clone github **ssh** repos with any terminal.
